<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>keKit</text>

        <Action name="keGrid">
        <icon></icon>
        <text>keGrid</text>
        <whatsThis>Relative Grid</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>'</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="keCenter">
        <icon></icon>
        <text>keCenter</text>
        <whatsThis>Center Layer</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>1</activationFlags>
        <activationConditions>8</activationConditions>
        <shortcut>ctrl+alt+*</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
        
        <Action name="keCenterH">
        <icon></icon>
        <text>keCenterH</text>
        <whatsThis>Center Layer Horizontally</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>1</activationFlags>
        <activationConditions>8</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
        
        <Action name="keCenterV">
        <icon></icon>
        <text>keCenterV</text>
        <whatsThis>Center Layer Vertically</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>1</activationFlags>
        <activationConditions>8</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="keFitBounds">
        <icon></icon>
        <text>keFitBounds</text>
        <whatsThis>...</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>1</activationFlags>
        <activationConditions>8</activationConditions>
        <shortcut>ctrl+alt+/</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="keHalve">
        <icon></icon>
        <text>keHalve</text>
        <whatsThis>...</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>1</activationFlags>
        <activationConditions>8</activationConditions>
        <shortcut>ctrl+alt+-</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

        <Action name="keDouble">
        <icon></icon>
        <text>keDouble</text>
        <whatsThis>...</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>1</activationFlags>
        <activationConditions>8</activationConditions>
        <shortcut>ctrl+alt++</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>

    </Actions>
</ActionCollection>
